package net.gongmingqm10.traintimer.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.gongmingqm10.traintimer.data.Station;
import net.gongmingqm10.traintimer.data.Trip;

import net.gongmingqm10.traintimer.data.StationDao;
import net.gongmingqm10.traintimer.data.TripDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationDaoConfig;
    private final DaoConfig tripDaoConfig;

    private final StationDao stationDao;
    private final TripDao tripDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        tripDaoConfig = daoConfigMap.get(TripDao.class).clone();
        tripDaoConfig.initIdentityScope(type);

        stationDao = new StationDao(stationDaoConfig, this);
        tripDao = new TripDao(tripDaoConfig, this);

        registerDao(Station.class, stationDao);
        registerDao(Trip.class, tripDao);
    }
    
    public void clear() {
        stationDaoConfig.getIdentityScope().clear();
        tripDaoConfig.getIdentityScope().clear();
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public TripDao getTripDao() {
        return tripDao;
    }

}
