package net.gongmingqm10.traintimer.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "STATION".
 */
public class Station implements Serializable {

    private Long id;
    private String name;
    private String englishName;
    private String code;

    public Station() {
    }

    public Station(Long id) {
        this.id = id;
    }

    public Station(Long id, String name, String englishName, String code) {
        this.id = id;
        this.name = name;
        this.englishName = englishName;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
